#ifndef CONFIG_H
#define CONFIG_H

#define MAX_FILENAME_SIZE (20)
#define BLOCKID_SIZE (14)
#define BLOCKOFFSET_SIZE (10)
#define NUM_DIRECT_ADDRESS (10)
#define NUM_INDIRECT_ADDRESS (1)
#define SYSTEM_SIZE (16*1024*1024)
#define BLOCK_SIZE (1024)
#define BLOCK_NUM (SYSTEM_SIZE/BLOCK_SIZE)
#define ADDRESS_LENGTH (24)
#define BLOCK_BIT (14)
#define OFFSET (10)
#define MAX_PATH (1000)
#define INODE_BITMAP_SIZE (2*1024)
#define BLOCK_BITMAP_SIZE (2*1024)
#define INODE_TABLE_SIZE (2*1024*1024)
#define INODE_BITMAP_START BLOCK_SIZE
#define BLOCK_BITMAP_START (INODE_BITMAP_START+INODE_BITMAP_SIZE)
#define INODE_TABLE_START (BLOCK_BITMAP_START+BLOCK_BITMAP_SIZE)
#define MAX_FILE_SIZE (1024*1024)
#define FILE_MODE (0)
#define DENTRY_MODE (1)
#define HOME "unix.os"
#define root_dir "Home"

// size in bytes
#endif
